name: Python Unit Tests

# Trigger workflow on push or pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify your Python version

    # Step 3: Install dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add your dependencies here if you have any, e.g.
        # pip install -r requirements.txt

    # Step 4: Run unit tests
    - name: Run tests
      run: |
        python -m unittest discover -s . -p "test_*.py"
